package org.iesvegademijas.hibernate;
// Generated 9 oct. 2022 14:12:31 by Hibernate Tools 5.6.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Fabricante generated by hbm2java
 */
public class Fabricante implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private Set productos = new HashSet(0);

	public Fabricante() {
	}

	public Fabricante(String nombre) {
		this.nombre = nombre;
	}

	public Fabricante(String nombre, Set productos) {
		this.nombre = nombre;
		this.productos = productos;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

	@Override
	public String toString() {
		return "Fabricante [codigo=" + codigo + ", nombre=" + nombre + "]";
	}
	
}
