package org.iesvegademijas.hibernate;
// Generated 9 oct. 2022 14:12:31 by Hibernate Tools 5.6.9.Final

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer codigo;
	private Fabricante fabricante;
	private String nombre;
	private double precio;
	

	public Producto() {
	}

	public Producto(Fabricante fabricante, String nombre, double precio) {
		this.fabricante = fabricante;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Fabricante getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(Fabricante fabricante) {
		this.fabricante = fabricante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}
	
	@Override
	public String toString() {
		return "Producto [codigo=" + codigo + ", fabricante=" + fabricante + ", nombre=" + nombre + ", precio=" + precio
				+ "]";
	}


}
