package es.iesvegademijas.streams;
// Generated 28 oct. 2022 5:19:17 by Hibernate Tools 5.6.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	
	
	private Integer codigo;
	private String nombre;
	private double presupuesto;
	private double gastos;
	private Set empleados = new HashSet(0);

	public Departamento() {
	}

	public Departamento(String nombre, double presupuesto, double gastos) {
		this.nombre = nombre;
		this.presupuesto = presupuesto;
		this.gastos = gastos;
	}

	public Departamento(String nombre, double presupuesto, double gastos, Set empleados) {
		this.nombre = nombre;
		this.presupuesto = presupuesto;
		this.gastos = gastos;
		this.empleados = empleados;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

	public double getGastos() {
		return this.gastos;
	}

	public void setGastos(double gastos) {
		this.gastos = gastos;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public String toString() {
		return "Departamento [codigo=" + codigo + ", nombre=" + nombre + ", presupuesto=" + presupuesto + ", gastos="
				+ gastos + "]";
	}
}
