package org.iesvdm.streams;
// Generated 15 dic. 2022 23:59:33 by Hibernate Tools 5.6.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Comercial generated by hbm2java
 */
public class Comercial implements java.io.Serializable {
	
	private Integer id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private Float comisión;
	private Set pedidos = new HashSet(0);

	public Comercial() {
	}

	public Comercial(String nombre, String apellido1) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
	}

	public Comercial(String nombre, String apellido1, String apellido2, Float comisión, Set pedidos) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.comisión = comisión;
		this.pedidos = pedidos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public Float getComisión() {
		return this.comisión;
	}

	public void setComisión(Float comisión) {
		this.comisión = comisión;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}
	
	@Override
	public String toString() {
		return "Comercial [id=" + id + ", nombre=" + nombre + ", apellido1=" + apellido1 + ", apellido2=" + apellido2
				+ ", comisión=" + comisión + "]";
	}

}
